# Фильмы

## Получить список фильмов
GET http://localhost:53000/movies HTTP/1.1
Accept: application/json
###

## Получение промо-фильма
GET http://localhost:53000/movies/promo HTTP/1.1
Accept: application/json

###

## Получение конкретного фильма
GET http://localhost:53000/movies/63bb49782c331a1be79c2534 HTTP/1.1
Accept: application/json
###


## Добавить новый фильм
POST http://localhost:53000/movies/create HTTP/1.1
Content-Type: application/json

{
  "title": "Голодные игры",
  "description": "Деспотичное государство ежегодно устраивает показательные игры на выживание, за которыми в прямом эфире следит весь мир.",
  "publishingDate": "2022-10-21T22:55:33.903Z",
  "genre": "thriller",
  "releaseYear": 2013,
  "previewPath": "https://www.what-to-watch.ru/hunger_games_preview",
  "moviePath": "https://www.what-to-watch.ru/hunger_games",
  "actors": [
    "Дженнифер Лоуренс",
    "Джош Хатчерсон",
    "Лиам Хемсворт"
  ],
  "director": "Гэри Росс",
  "durationInMinutes": 0,
  "userId": "6383d47aed383bd2e38c2d32",
  "posterPath": "hunger_games_poster.jpg",
  "backgroundImagePath": "hunger_games_bg.jpg",
  "backgroundColor": "green"
}

###


## Редактирование карточки фильма
PATCH http://localhost:53000/movies/638d07890c09034b948986d9 HTTP/1.1
Content-Type: application/json

{
  "title": "Король лев",
  "description": "У величественного Короля-Льва Муфасы рождается наследник по имени Симба. Уже в детстве любознательный малыш становится жертвой интриг своего завистливого дяди Шрама, мечтающего о власти. Симба познаёт горе утраты, предательство и изгнание, но в конце концов обретает верных друзей и находит любимую. Закалённый испытаниями, он в нелёгкой борьбе отвоёвывает своё законное место в «Круге жизни», осознав, что значит быть настоящим Королём.",
  "publishingDate": "2022-10-22T22:55:33.903Z",
  "genre": "drama",
  "releaseYear": 2013,
  "previewPath": "https://www.what-to-watch.ru/lion_ling_preview",
  "moviePath": "https://www.what-to-watch.ru/lion_king",
  "actors": [
    "Джеймс Эрл Джонс",
    "Мэттью Бродерик",
    "Джонатан Тейлор Томас"
  ],
  "director": "Роджер Алерс",
  "durationInMinutes": 0,
  "userId": "6383d47aed383bd2e38c2d32",
  "posterPath": "lion_king_poster.jpg",
  "backgroundImagePath": "lion_king_bg.jpg",
  "backgroundColor": "orange",
  "isPromo": true
}
